---
# Personal-only Mac App Store apps. Excluded on non-personal machines via
# .chezmoiignore.tmpl.
mac_app_store_apps_personal:
  Kindle: 302584613
  "Microsoft 365": 1450038993
  Paprika: 1303222628
  "Poolsuite FM": 1514817810
  "Proton Pass for Safari": 6502835663
  TestFlight: 899247664
  TickTick: 966085870
  "UTM Virtual Machines": 1538878817
  WireGuard: 1451685025
  "Yubico Authenticator": 1497506650
