[vscode]

[vscode.extension_sets]
# Extension sets can be reused across multiple profiles
core = [
  "blueglassblock.better-json5",  # JSON5 language server
  "editorconfig.editorconfig",  # EditorConfig support, see https://editorconfig.org/
  "hverlin.mise-vscode",  # Env vars, local tools, tasks all-in-one
  "jimeh.actionlint",  # GitHub Actions linter
  "mechatroner.rainbow-csv",  # Improves CSV viewing
  "ms-azure-devops.azure-pipelines",  # Azure Pipelines support
  "oderwat.indent-rainbow",  # Improves indent visibility
  "owenlamont.ryl",  # YAML linter/formatter
  "redhat.vscode-yaml",  # Core YAML support
  "rvben.rumdl",  # Markdown linter/formatter
  "tekumara.typos-vscode",  # Intelligent spell checker
  "tombi-toml.tombi",  # TOML linter/formatter
  "usernamehw.errorlens",  # Highlights errors and warnings inline
]

jupyter = [
  "ms-toolsai.jupyter",  # Jupyter extension
]

python = [
  "astral-sh.ty",  # Type checking and language server, also replaces Pylance
  "charliermarsh.ruff",  # Python linter and formatter
  "ms-python.debugpy",  # Python debugger
  "ms-python.python",  # Core extension for Python support
  "ms-python.vscode-python-envs",  # Python environment management, integrates with uv
  "samuelcolvin.jinjahtml",  # Support for jinja templates
]

containers = [
  "ms-vscode-remote.remote-containers",  # Devcontainer support
]

[[vscode.profiles]]
name = "Default"
# Default profile doesn't have a custom icon in the VS Code UI
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/default.json"]
extension_sets = []
extensions = [
  "bardleware.sandstorm",  # Red theme to act as an indicator that you need to choose a profile
]

[[vscode.profiles]]
name = "Chezmoi"
icon = "home"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/python.json"]
extension_sets = ["core", "python"]
extensions = [
  "ms-vscode.powershell",  # PowerShell extension
]
# Should figure out a way to disable redhat.vscode-yaml for this profile, since it throws all kinds of linting errors about *.yaml.tmpl files

[[vscode.profiles]]
name = "Kubernetes"
icon = "server"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/python.json", ".chezmoitemplates/vscode/profile-settings/kubernetes.json"]
extension_sets = ["core", "python"]
extensions = [
  "ms-kubernetes-tools.vscode-kubernetes-tools",
]

[[vscode.profiles]]
name = "Nix"
icon = "terminal-linux"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/nix.json"]
extension_sets = ["core", "containers"]
extensions = [
  "jnoortheen.nix-ide",  # Nix language server
  "signageos.signageos-vscode-sops",  # SOPS support for secret management
]

[[vscode.profiles]]
name = "PowerShell"
icon = "terminal"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/powershell.json"]
extension_sets = ["core"]
extensions = [
  "ms-vscode.powershell",  # PowerShell extension
]

[[vscode.profiles]]
name = "Python"
icon = "snake"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/python.json"]
extension_sets = ["core", "python", "jupyter"]
extensions = []

[[vscode.profiles]]
name = "Terraform"
icon = "paintcan"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/python.json", ".chezmoitemplates/vscode/profile-settings/terraform.json"]
extension_sets = ["core", "python"]
extensions =  [
  "hashicorp.terraform",
]

[[vscode.profiles]]
name = "Web"
icon = "compass"
settings_files = [".chezmoitemplates/vscode/reusable-settings/core.json", ".chezmoitemplates/vscode/profile-settings/web.json"]
extension_sets = ["core"]
extensions = [
  "biomejs.biome",
  "deque-systems.vscode-axe-linter",
  "ms-vscode.live-server",
]
